export const SUCCESS = 'SUCCESS';
export const ERROR_OCCURED = 'ERROR_OCCURED';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const RESET_SUCCESS_MESSAGE = 'RESET_SUCCESS_MESSAGE';

export const PURCHASE_PRODUCT = 'PURCHASE_PRODUCT';

export const FETCH_QUERY_PRODUCTS = 'FETCH_QUERY_PRODUCTS';
